namespace nspector.Native.NVAPI2;

internal enum NVDRS_SETTING_LOCATION
{
	NVDRS_CURRENT_PROFILE_LOCATION,
	NVDRS_GLOBAL_PROFILE_LOCATION,
	NVDRS_BASE_PROFILE_LOCATION,
	NVDRS_DEFAULT_PROFILE_LOCATION
}
