<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HD-Player</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWPF>True</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net35</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Page Remove="BlueStacks.Player/WpfTextBoxControl.xaml" />
    <Page Include="BlueStacks.Player/WpfTextBoxControl.xaml" Generator="MSBuild:Compile" SubType="Designer" LogicalName="wpftextboxcontrol.xaml" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="HD-Common" />
    <Reference Include="System.Core">
      <HintPath>../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.12/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="BstkTypeLib" />
    <Reference Include="Newtonsoft.Json" />
    <Reference Include="SystemInfo" />
    <Reference Include="System.Core">
      <HintPath>../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.12/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualBasic">
      <HintPath>../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.12/Microsoft.VisualBasic.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualBasic">
      <HintPath>../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.12/Microsoft.VisualBasic.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/10.0.12/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json" />
  </ItemGroup>
</Project>