namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS : uint
{
	NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NONE = 0u,
	NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_PERF_TO_9X = 1u,
	NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_NUM_VALUES = 2u,
	NGX_DLSS_OVERRIDE_OPTIMAL_SETTINGS_DEFAULT = 0u
}
