namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_NGX_DLSS_SR_MODE : uint
{
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_PERFORMANCE = 0u,
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_BALANCED = 1u,
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_QUALITY = 2u,
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_SNIPPET_CONTROLLED = 3u,
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_DLAA = 4u,
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_ULTRA_PERFORMANCE = 5u,
	NGX_DLSS_SR_MODE_NGX_DLSS_SR_MODE_CUSTOM = 6u,
	NGX_DLSS_SR_MODE_NUM_VALUES = 7u,
	NGX_DLSS_SR_MODE_DEFAULT = 3u
}
