namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_PRERENDERLIMIT : uint
{
	PRERENDERLIMIT_MIN = 0u,
	PRERENDERLIMIT_MAX = 255u,
	PRERENDERLIMIT_APP_CONTROLLED = 0u,
	PRERENDERLIMIT_NUM_VALUES = 3u,
	PRERENDERLIMIT_DEFAULT = 0u
}
