namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_TMON_LEVEL : uint
{
	OGL_TMON_LEVEL_DISABLE = 0u,
	OGL_TMON_LEVEL_CRITICAL = 1u,
	OGL_TMON_LEVEL_WARNING = 2u,
	OGL_TMON_LEVEL_INFORMATION = 3u,
	OGL_TMON_LEVEL_MOST = 4u,
	OGL_TMON_LEVEL_VERBOSE = 5u,
	OGL_TMON_LEVEL_NUM_VALUES = 6u,
	OGL_TMON_LEVEL_DEFAULT = 4u
}
