namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SLI_PREDEFINED_MODE_DX10 : uint
{
	SLI_PREDEFINED_MODE_DX10_AUTOSELECT = 0u,
	SLI_PREDEFINED_MODE_DX10_FORCE_SINGLE = 1u,
	SLI_PREDEFINED_MODE_DX10_FORCE_AFR = 2u,
	SLI_PREDEFINED_MODE_DX10_FORCE_AFR2 = 3u,
	SLI_PREDEFINED_MODE_DX10_FORCE_SFR = 4u,
	SLI_PREDEFINED_MODE_DX10_FORCE_AFR_OF_SFR__FALLBACK_3AFR = 5u,
	SLI_PREDEFINED_MODE_DX10_NUM_VALUES = 6u,
	SLI_PREDEFINED_MODE_DX10_DEFAULT = 0u
}
