namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_QUALITY_ENHANCEMENT_SUBSTITUTION : uint
{
	QUALITY_ENHANCEMENT_SUBSTITUTION_NO_SUBSTITUTION = 0u,
	QUALITY_ENHANCEMENT_SUBSTITUTION_HIGHQUALITY_BECOMES_QUALITY = 1u,
	QUALITY_ENHANCEMENT_SUBSTITUTION_NUM_VALUES = 2u,
	QUALITY_ENHANCEMENT_SUBSTITUTION_DEFAULT = 0u
}
