namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VRRFEATUREINDICATOR : uint
{
	VRRFEATUREINDICATOR_DISABLED = 0u,
	VRRFEATUREINDICATOR_ENABLED = 1u,
	VRRFEATUREINDICATOR_NUM_VALUES = 2u,
	VRRFEATUREINDICATOR_DEFAULT = 1u
}
