namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VRROVERLAYINDICATOR : uint
{
	VRROVERLAYINDICATOR_DISABLED = 0u,
	VRROVERLAYINDICATOR_ENABLED = 1u,
	VRROVERLAYINDICATOR_NUM_VALUES = 2u,
	VRROVERLAYINDICATOR_DEFAULT = 1u
}
