namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SLI_PREDEFINED_MODE : uint
{
	SLI_PREDEFINED_MODE_AUTOSELECT = 0u,
	SLI_PREDEFINED_MODE_FORCE_SINGLE = 1u,
	SLI_PREDEFINED_MODE_FORCE_AFR = 2u,
	SLI_PREDEFINED_MODE_FORCE_AFR2 = 3u,
	SLI_PREDEFINED_MODE_FORCE_SFR = 4u,
	SLI_PREDEFINED_MODE_FORCE_AFR_OF_SFR__FALLBACK_3AFR = 5u,
	SLI_PREDEFINED_MODE_NUM_VALUES = 6u,
	SLI_PREDEFINED_MODE_DEFAULT = 0u
}
