namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_AA_MODE_GAMMACORRECTION : uint
{
	AA_MODE_GAMMACORRECTION_MASK = 3u,
	AA_MODE_GAMMACORRECTION_OFF = 0u,
	AA_MODE_GAMMACORRECTION_ON_IF_FOS = 1u,
	AA_MODE_GAMMACORRECTION_ON_ALWAYS = 2u,
	AA_MODE_GAMMACORRECTION_MAX = 2u,
	AA_MODE_GAMMACORRECTION_DEFAULT = 0u,
	AA_MODE_GAMMACORRECTION_DEFAULT_TESLA = 2u,
	AA_MODE_GAMMACORRECTION_DEFAULT_FERMI = 2u,
	AA_MODE_GAMMACORRECTION_NUM_VALUES = 8u
}
