namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VSYNC_BEHAVIOR_FLAGS : uint
{
	VSYNC_BEHAVIOR_FLAGS_NONE = 0u,
	VSYNC_BEHAVIOR_FLAGS_DEFAULT = 0u,
	VSYNC_BEHAVIOR_FLAGS_IGNORE_FLIPINTERVAL_MULTIPLE = 1u,
	VSYNC_BEHAVIOR_FLAGS_NUM_VALUES = 3u
}
