namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_WKS_STEREO_DONGLE_SUPPORT : uint
{
	WKS_STEREO_DONGLE_SUPPORT_OFF = 0u,
	WKS_STEREO_DONGLE_SUPPORT_DAC = 1u,
	WKS_STEREO_DONGLE_SUPPORT_DLP = 2u,
	WKS_STEREO_DONGLE_SUPPORT_NUM_VALUES = 3u,
	WKS_STEREO_DONGLE_SUPPORT_DEFAULT = 1u
}
