namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VRRREQUESTSTATE : uint
{
	VRRREQUESTSTATE_DISABLED = 0u,
	VRRREQUESTSTATE_FULLSCREEN_ONLY = 1u,
	VRRREQUESTSTATE_FULLSCREEN_AND_WINDOWED = 2u,
	VRRREQUESTSTATE_NUM_VALUES = 3u,
	VRRREQUESTSTATE_DEFAULT = 1u
}
