namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_AA_BEHAVIOR_FLAGS : uint
{
	AA_BEHAVIOR_FLAGS_NONE = 0u,
	AA_BEHAVIOR_FLAGS_TREAT_OVERRIDE_AS_APP_CONTROLLED = 1u,
	AA_BEHAVIOR_FLAGS_TREAT_OVERRIDE_AS_ENHANCE = 2u,
	AA_BEHAVIOR_FLAGS_DISABLE_OVERRIDE = 3u,
	AA_BEHAVIOR_FLAGS_TREAT_ENHANCE_AS_APP_CONTROLLED = 4u,
	AA_BEHAVIOR_FLAGS_TREAT_ENHANCE_AS_OVERRIDE = 8u,
	AA_BEHAVIOR_FLAGS_DISABLE_ENHANCE = 12u,
	AA_BEHAVIOR_FLAGS_MAP_VCAA_TO_MULTISAMPLING = 65536u,
	AA_BEHAVIOR_FLAGS_SLI_DISABLE_TRANSPARENCY_SUPERSAMPLING = 131072u,
	AA_BEHAVIOR_FLAGS_DISABLE_CPLAA = 262144u,
	AA_BEHAVIOR_FLAGS_SKIP_RT_DIM_CHECK_FOR_ENHANCE = 524288u,
	AA_BEHAVIOR_FLAGS_DISABLE_SLIAA = 1048576u,
	AA_BEHAVIOR_FLAGS_DEFAULT = 0u,
	AA_BEHAVIOR_FLAGS_AA_RT_BPP_DIV_4 = 4026531840u,
	AA_BEHAVIOR_FLAGS_AA_RT_BPP_DIV_4_SHIFT = 28u,
	AA_BEHAVIOR_FLAGS_NON_AA_RT_BPP_DIV_4 = 251658240u,
	AA_BEHAVIOR_FLAGS_NON_AA_RT_BPP_DIV_4_SHIFT = 24u,
	AA_BEHAVIOR_FLAGS_MASK = 4280221711u,
	AA_BEHAVIOR_FLAGS_NUM_VALUES = 18u
}
