namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_PS_SHADERDISKCACHE_MAX_SIZE : uint
{
	PS_SHADERDISKCACHE_MAX_SIZE_MIN = 0u,
	PS_SHADERDISKCACHE_MAX_SIZE_MAX = uint.MaxValue,
	PS_SHADERDISKCACHE_MAX_SIZE_NUM_VALUES = 2u,
	PS_SHADERDISKCACHE_MAX_SIZE_DEFAULT = 8192u
}
