namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE : uint
{
	SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_OFF = 0u,
	SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_ON = 1u,
	SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_NUM_VALUES = 2u,
	SET_POWER_THROTTLE_FOR_PCIe_COMPLIANCE_DEFAULT = 0u
}
