namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_EXPORT_PERF_COUNTERS_DX9_ONLY : uint
{
	EXPORT_PERF_COUNTERS_DX9_ONLY_OFF = 0u,
	EXPORT_PERF_COUNTERS_DX9_ONLY_ON = 1u,
	EXPORT_PERF_COUNTERS_DX9_ONLY_NUM_VALUES = 2u,
	EXPORT_PERF_COUNTERS_DX9_ONLY_DEFAULT = 0u
}
