namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_CPL_PREFER_DXPRESENT : uint
{
	OGL_CPL_PREFER_DXPRESENT_PREFER_DISABLED = 0u,
	OGL_CPL_PREFER_DXPRESENT_PREFER_ENABLED = 1u,
	OGL_CPL_PREFER_DXPRESENT_AUTO = 2u,
	OGL_CPL_PREFER_DXPRESENT_NUM_VALUES = 3u,
	OGL_CPL_PREFER_DXPRESENT_DEFAULT = 2u
}
