namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_CPL_GDI_COMPATIBILITY : uint
{
	OGL_CPL_GDI_COMPATIBILITY_PREFER_DISABLED = 0u,
	OGL_CPL_GDI_COMPATIBILITY_PREFER_ENABLED = 1u,
	OGL_CPL_GDI_COMPATIBILITY_AUTO = 2u,
	OGL_CPL_GDI_COMPATIBILITY_NUM_VALUES = 3u,
	OGL_CPL_GDI_COMPATIBILITY_DEFAULT = 2u
}
