namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_WKS_API_STEREO_EYES_EXCHANGE : uint
{
	WKS_API_STEREO_EYES_EXCHANGE_OFF = 0u,
	WKS_API_STEREO_EYES_EXCHANGE_ON = 1u,
	WKS_API_STEREO_EYES_EXCHANGE_NUM_VALUES = 2u,
	WKS_API_STEREO_EYES_EXCHANGE_DEFAULT = 0u
}
