namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_MAXWELL_B_SAMPLE_INTERLEAVE : uint
{
	MAXWELL_B_SAMPLE_INTERLEAVE_OFF = 0u,
	MAXWELL_B_SAMPLE_INTERLEAVE_ON = 1u,
	MAXWELL_B_SAMPLE_INTERLEAVE_NUM_VALUES = 2u,
	MAXWELL_B_SAMPLE_INTERLEAVE_DEFAULT = 0u
}
