namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_WKS_STEREO_SWAP_MODE : uint
{
	WKS_STEREO_SWAP_MODE_APPLICATION_CONTROL = 0u,
	WKS_STEREO_SWAP_MODE_PER_EYE = 1u,
	WKS_STEREO_SWAP_MODE_PER_EYE_PAIR = 2u,
	WKS_STEREO_SWAP_MODE_LEGACY_BEHAVIOR = 3u,
	WKS_STEREO_SWAP_MODE_PER_EYE_FOR_SWAP_GROUP = 4u,
	WKS_STEREO_SWAP_MODE_NUM_VALUES = 5u,
	WKS_STEREO_SWAP_MODE_DEFAULT = 0u
}
