namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_ANISO_MODE_LEVEL : uint
{
	ANISO_MODE_LEVEL_MASK = 65535u,
	ANISO_MODE_LEVEL_NONE_POINT = 0u,
	ANISO_MODE_LEVEL_NONE_LINEAR = 1u,
	ANISO_MODE_LEVEL_MAX = 16u,
	ANISO_MODE_LEVEL_DEFAULT = 1u,
	ANISO_MODE_LEVEL_NUM_VALUES = 5u
}
