namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VSYNCVRRCONTROL : uint
{
	VSYNCVRRCONTROL_DISABLE = 0u,
	VSYNCVRRCONTROL_ENABLE = 1u,
	VSYNCVRRCONTROL_NOTSUPPORTED = 2677346958u,
	VSYNCVRRCONTROL_NUM_VALUES = 3u,
	VSYNCVRRCONTROL_DEFAULT = 1u
}
