namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VRR_APP_OVERRIDE : uint
{
	VRR_APP_OVERRIDE_ALLOW = 0u,
	VRR_APP_OVERRIDE_FORCE_OFF = 1u,
	VRR_APP_OVERRIDE_DISALLOW = 2u,
	VRR_APP_OVERRIDE_ULMB = 3u,
	VRR_APP_OVERRIDE_FIXED_REFRESH = 4u,
	VRR_APP_OVERRIDE_NUM_VALUES = 5u,
	VRR_APP_OVERRIDE_DEFAULT = 0u
}
