namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SHIM_RENDERING_MODE : uint
{
	SHIM_RENDERING_MODE_INTEGRATED = 0u,
	SHIM_RENDERING_MODE_ENABLE = 1u,
	SHIM_RENDERING_MODE_USER_EDITABLE = 2u,
	SHIM_RENDERING_MODE_MASK = 3u,
	SHIM_RENDERING_MODE_VIDEO_MASK = 4u,
	SHIM_RENDERING_MODE_VARYING_BIT = 8u,
	SHIM_RENDERING_MODE_AUTO_SELECT = 16u,
	SHIM_RENDERING_MODE_OVERRIDE_BIT = 2147483648u,
	SHIM_RENDERING_MODE_NUM_VALUES = 8u,
	SHIM_RENDERING_MODE_DEFAULT = 16u
}
