namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VRR_APP_OVERRIDE_REQUEST_STATE : uint
{
	VRR_APP_OVERRIDE_REQUEST_STATE_ALLOW = 0u,
	VRR_APP_OVERRIDE_REQUEST_STATE_FORCE_OFF = 1u,
	VRR_APP_OVERRIDE_REQUEST_STATE_DISALLOW = 2u,
	VRR_APP_OVERRIDE_REQUEST_STATE_ULMB = 3u,
	VRR_APP_OVERRIDE_REQUEST_STATE_FIXED_REFRESH = 4u,
	VRR_APP_OVERRIDE_REQUEST_STATE_NUM_VALUES = 5u,
	VRR_APP_OVERRIDE_REQUEST_STATE_DEFAULT = 0u
}
