namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_BATTERY_BOOST_APP_FPS : uint
{
	BATTERY_BOOST_APP_FPS_MIN = 1u,
	BATTERY_BOOST_APP_FPS_MAX = 1023u,
	BATTERY_BOOST_APP_FPS_NO_OVERRIDE = 0u,
	BATTERY_BOOST_APP_FPS_NUM_VALUES = 3u,
	BATTERY_BOOST_APP_FPS_DEFAULT = 0u
}
