namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_QUALITY_ENHANCEMENTS : uint
{
	OGL_QUALITY_ENHANCEMENTS_HQUAL = 4294967286u,
	OGL_QUALITY_ENHANCEMENTS_QUAL = 0u,
	OGL_QUALITY_ENHANCEMENTS_PERF = 10u,
	OGL_QUALITY_ENHANCEMENTS_HPERF = 20u,
	OGL_QUALITY_ENHANCEMENTS_NUM_VALUES = 4u,
	OGL_QUALITY_ENHANCEMENTS_DEFAULT = 0u
}
