namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_ANISO_MODE_SELECTOR : uint
{
	ANISO_MODE_SELECTOR_MASK = 15u,
	ANISO_MODE_SELECTOR_APP = 0u,
	ANISO_MODE_SELECTOR_USER = 1u,
	ANISO_MODE_SELECTOR_COND = 2u,
	ANISO_MODE_SELECTOR_MAX = 2u,
	ANISO_MODE_SELECTOR_DEFAULT = 0u,
	ANISO_MODE_SELECTOR_NUM_VALUES = 6u
}
