namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_AA_MODE_ALPHATOCOVERAGE : uint
{
	AA_MODE_ALPHATOCOVERAGE_MODE_MASK = 4u,
	AA_MODE_ALPHATOCOVERAGE_MODE_OFF = 0u,
	AA_MODE_ALPHATOCOVERAGE_MODE_ON = 4u,
	AA_MODE_ALPHATOCOVERAGE_MODE_MAX = 4u,
	AA_MODE_ALPHATOCOVERAGE_NUM_VALUES = 4u,
	AA_MODE_ALPHATOCOVERAGE_DEFAULT = 0u
}
