namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_DEFAULT_SWAP_INTERVAL : uint
{
	OGL_DEFAULT_SWAP_INTERVAL_TEAR = 0u,
	OGL_DEFAULT_SWAP_INTERVAL_VSYNC_ONE = 1u,
	OGL_DEFAULT_SWAP_INTERVAL_VSYNC = 1u,
	OGL_DEFAULT_SWAP_INTERVAL_VALUE_MASK = 65535u,
	OGL_DEFAULT_SWAP_INTERVAL_FORCE_MASK = 4026531840u,
	OGL_DEFAULT_SWAP_INTERVAL_FORCE_OFF = 4026531840u,
	OGL_DEFAULT_SWAP_INTERVAL_FORCE_ON = 268435456u,
	OGL_DEFAULT_SWAP_INTERVAL_APP_CONTROLLED = 0u,
	OGL_DEFAULT_SWAP_INTERVAL_DISABLE = uint.MaxValue,
	OGL_DEFAULT_SWAP_INTERVAL_NUM_VALUES = 9u,
	OGL_DEFAULT_SWAP_INTERVAL_DEFAULT = 1u
}
