namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_VRPRERENDERLIMIT : uint
{
	VRPRERENDERLIMIT_MIN = 0u,
	VRPRERENDERLIMIT_MAX = 255u,
	VRPRERENDERLIMIT_APP_CONTROLLED = 0u,
	VRPRERENDERLIMIT_DEFAULT = 1u,
	VRPRERENDERLIMIT_NUM_VALUES = 4u
}
