namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SHIM_MCCOMPAT : uint
{
	SHIM_MCCOMPAT_INTEGRATED = 0u,
	SHIM_MCCOMPAT_ENABLE = 1u,
	SHIM_MCCOMPAT_USER_EDITABLE = 2u,
	SHIM_MCCOMPAT_MASK = 3u,
	SHIM_MCCOMPAT_VIDEO_MASK = 4u,
	SHIM_MCCOMPAT_VARYING_BIT = 8u,
	SHIM_MCCOMPAT_AUTO_SELECT = 16u,
	SHIM_MCCOMPAT_OVERRIDE_BIT = 2147483648u,
	SHIM_MCCOMPAT_NUM_VALUES = 8u,
	SHIM_MCCOMPAT_DEFAULT = 16u
}
