namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL : uint
{
	OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ZERO_SCANLINES = 0u,
	OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_ONE_FULL_FRAME_OF_SCANLINES = 100u,
	OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_NUM_VALUES = 2u,
	OGL_DEFAULT_SWAP_INTERVAL_FRACTIONAL_DEFAULT = 0u
}
