namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_WKS_API_STEREO_MODE : uint
{
	WKS_API_STEREO_MODE_SHUTTER_GLASSES = 0u,
	WKS_API_STEREO_MODE_VERTICAL_INTERLACED = 1u,
	WKS_API_STEREO_MODE_TWINVIEW = 2u,
	WKS_API_STEREO_MODE_NV17_SHUTTER_GLASSES_AUTO = 3u,
	WKS_API_STEREO_MODE_NV17_SHUTTER_GLASSES_DAC0 = 4u,
	WKS_API_STEREO_MODE_NV17_SHUTTER_GLASSES_DAC1 = 5u,
	WKS_API_STEREO_MODE_COLOR_LINE = 6u,
	WKS_API_STEREO_MODE_COLOR_INTERLEAVED = 7u,
	WKS_API_STEREO_MODE_ANAGLYPH = 8u,
	WKS_API_STEREO_MODE_HORIZONTAL_INTERLACED = 9u,
	WKS_API_STEREO_MODE_SIDE_FIELD = 10u,
	WKS_API_STEREO_MODE_SUB_FIELD = 11u,
	WKS_API_STEREO_MODE_CHECKERBOARD = 12u,
	WKS_API_STEREO_MODE_INVERSE_CHECKERBOARD = 13u,
	WKS_API_STEREO_MODE_TRIDELITY_SL = 14u,
	WKS_API_STEREO_MODE_TRIDELITY_MV = 15u,
	WKS_API_STEREO_MODE_SEEFRONT = 16u,
	WKS_API_STEREO_MODE_STEREO_MIRROR = 17u,
	WKS_API_STEREO_MODE_FRAME_SEQUENTIAL = 18u,
	WKS_API_STEREO_MODE_AUTODETECT_PASSIVE_MODE = 19u,
	WKS_API_STEREO_MODE_AEGIS_DT_FRAME_SEQUENTIAL = 20u,
	WKS_API_STEREO_MODE_OEM_EMITTER_FRAME_SEQUENTIAL = 21u,
	WKS_API_STEREO_MODE_DP_INBAND = 22u,
	WKS_API_STEREO_MODE_USE_HW_DEFAULT = uint.MaxValue,
	WKS_API_STEREO_MODE_DEFAULT_GL = 3u,
	WKS_API_STEREO_MODE_NUM_VALUES = 25u,
	WKS_API_STEREO_MODE_DEFAULT = 0u
}
