namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SLI_PREDEFINED_GPU_COUNT_DX10 : uint
{
	SLI_PREDEFINED_GPU_COUNT_DX10_AUTOSELECT = 0u,
	SLI_PREDEFINED_GPU_COUNT_DX10_ONE = 1u,
	SLI_PREDEFINED_GPU_COUNT_DX10_TWO = 2u,
	SLI_PREDEFINED_GPU_COUNT_DX10_THREE = 3u,
	SLI_PREDEFINED_GPU_COUNT_DX10_FOUR = 4u,
	SLI_PREDEFINED_GPU_COUNT_DX10_NUM_VALUES = 5u,
	SLI_PREDEFINED_GPU_COUNT_DX10_DEFAULT = 0u
}
