namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_PS_TEXFILTER_BILINEAR_IN_ANISO : uint
{
	PS_TEXFILTER_BILINEAR_IN_ANISO_OFF = 0u,
	PS_TEXFILTER_BILINEAR_IN_ANISO_ON = 1u,
	PS_TEXFILTER_BILINEAR_IN_ANISO_NUM_VALUES = 2u,
	PS_TEXFILTER_BILINEAR_IN_ANISO_DEFAULT = 0u
}
