namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_SLI_MULTICAST : uint
{
	OGL_SLI_MULTICAST_DISABLE = 0u,
	OGL_SLI_MULTICAST_ENABLE = 1u,
	OGL_SLI_MULTICAST_FORCE_DISABLE = 2u,
	OGL_SLI_MULTICAST_ALLOW_MOSAIC = 4u,
	OGL_SLI_MULTICAST_NUM_VALUES = 4u,
	OGL_SLI_MULTICAST_DEFAULT = 0u
}
