namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_OVERLAY_PIXEL_TYPE : uint
{
	OGL_OVERLAY_PIXEL_TYPE_NONE = 0u,
	OGL_OVERLAY_PIXEL_TYPE_CI = 1u,
	OGL_OVERLAY_PIXEL_TYPE_RGBA = 2u,
	OGL_OVERLAY_PIXEL_TYPE_CI_AND_RGBA = 3u,
	OGL_OVERLAY_PIXEL_TYPE_NUM_VALUES = 4u,
	OGL_OVERLAY_PIXEL_TYPE_DEFAULT = 1u
}
