namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_QUALITY_ENHANCEMENTS : uint
{
	QUALITY_ENHANCEMENTS_HIGHQUALITY = 4294967286u,
	QUALITY_ENHANCEMENTS_QUALITY = 0u,
	QUALITY_ENHANCEMENTS_PERFORMANCE = 10u,
	QUALITY_ENHANCEMENTS_HIGHPERFORMANCE = 20u,
	QUALITY_ENHANCEMENTS_NUM_VALUES = 4u,
	QUALITY_ENHANCEMENTS_DEFAULT = 0u
}
