namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_SLI_PREDEFINED_GPU_COUNT : uint
{
	SLI_PREDEFINED_GPU_COUNT_AUTOSELECT = 0u,
	SLI_PREDEFINED_GPU_COUNT_ONE = 1u,
	SLI_PREDEFINED_GPU_COUNT_TWO = 2u,
	SLI_PREDEFINED_GPU_COUNT_THREE = 3u,
	SLI_PREDEFINED_GPU_COUNT_FOUR = 4u,
	SLI_PREDEFINED_GPU_COUNT_NUM_VALUES = 5u,
	SLI_PREDEFINED_GPU_COUNT_DEFAULT = 0u
}
