namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_EVENT_LOG_SEVERITY_THRESHOLD : uint
{
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_DISABLE = 0u,
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_CRITICAL = 1u,
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_WARNING = 2u,
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_INFORMATION = 3u,
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_ALL = 4u,
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_NUM_VALUES = 5u,
	OGL_EVENT_LOG_SEVERITY_THRESHOLD_DEFAULT = 4u
}
