namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_AA_MODE_REPLAY : uint
{
	AA_MODE_REPLAY_SAMPLES_MASK = 112u,
	AA_MODE_REPLAY_SAMPLES_ONE = 0u,
	AA_MODE_REPLAY_SAMPLES_TWO = 16u,
	AA_MODE_REPLAY_SAMPLES_FOUR = 32u,
	AA_MODE_REPLAY_SAMPLES_EIGHT = 48u,
	AA_MODE_REPLAY_SAMPLES_MAX = 48u,
	AA_MODE_REPLAY_MODE_MASK = 15u,
	AA_MODE_REPLAY_MODE_OFF = 0u,
	AA_MODE_REPLAY_MODE_ALPHA_TEST = 1u,
	AA_MODE_REPLAY_MODE_PIXEL_KILL = 2u,
	AA_MODE_REPLAY_MODE_DYN_BRANCH = 4u,
	AA_MODE_REPLAY_MODE_OPTIMAL = 4u,
	AA_MODE_REPLAY_MODE_ALL = 8u,
	AA_MODE_REPLAY_MODE_MAX = 15u,
	AA_MODE_REPLAY_TRANSPARENCY = 35u,
	AA_MODE_REPLAY_DISALLOW_TRAA = 256u,
	AA_MODE_REPLAY_TRANSPARENCY_DEFAULT = 0u,
	AA_MODE_REPLAY_TRANSPARENCY_DEFAULT_TESLA = 0u,
	AA_MODE_REPLAY_TRANSPARENCY_DEFAULT_FERMI = 0u,
	AA_MODE_REPLAY_MASK = 383u,
	AA_MODE_REPLAY_NUM_VALUES = 20u,
	AA_MODE_REPLAY_DEFAULT = 0u
}
