namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_APPLICATION_PROFILE_NOTIFICATION_TIMEOUT : uint
{
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DISABLED = 0u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NINE_SECONDS = 9u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_FIFTEEN_SECONDS = 15u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_THIRTY_SECONDS = 30u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_ONE_MINUTE = 60u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_TWO_MINUTES = 120u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_NUM_VALUES = 6u,
	APPLICATION_PROFILE_NOTIFICATION_TIMEOUT_DEFAULT = 0u
}
