namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_PS_TEXFILTER_NO_NEG_LODBIAS : uint
{
	PS_TEXFILTER_NO_NEG_LODBIAS_OFF = 0u,
	PS_TEXFILTER_NO_NEG_LODBIAS_ON = 1u,
	PS_TEXFILTER_NO_NEG_LODBIAS_NUM_VALUES = 2u,
	PS_TEXFILTER_NO_NEG_LODBIAS_DEFAULT = 0u
}
