namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_REFRESH_RATE_OVERRIDE : uint
{
	REFRESH_RATE_OVERRIDE_APPLICATION_CONTROLLED = 0u,
	REFRESH_RATE_OVERRIDE_HIGHEST_AVAILABLE = 1u,
	REFRESH_RATE_OVERRIDE_LOW_LATENCY_RR_MASK = 4080u,
	REFRESH_RATE_OVERRIDE_NUM_VALUES = 3u,
	REFRESH_RATE_OVERRIDE_DEFAULT = 0u
}
