namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_PS_TEXFILTER_DISABLE_TRILIN_SLOPE : uint
{
	PS_TEXFILTER_DISABLE_TRILIN_SLOPE_OFF = 0u,
	PS_TEXFILTER_DISABLE_TRILIN_SLOPE_ON = 1u,
	PS_TEXFILTER_DISABLE_TRILIN_SLOPE_NUM_VALUES = 2u,
	PS_TEXFILTER_DISABLE_TRILIN_SLOPE_DEFAULT = 0u
}
