namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_NGX_DLSSG_MULTI_FRAME_COUNT : uint
{
	NGX_DLSSG_MULTI_FRAME_COUNT_MIN = 1u,
	NGX_DLSSG_MULTI_FRAME_COUNT_MAX = 15u,
	NGX_DLSSG_MULTI_FRAME_COUNT_DEFAULT = 1u,
	NGX_DLSSG_MULTI_FRAME_COUNT_NUM_VALUES = 3u
}
