namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_SINGLE_BACKDEPTH_BUFFER : uint
{
	OGL_SINGLE_BACKDEPTH_BUFFER_DISABLE = 0u,
	OGL_SINGLE_BACKDEPTH_BUFFER_ENABLE = 1u,
	OGL_SINGLE_BACKDEPTH_BUFFER_USE_HW_DEFAULT = uint.MaxValue,
	OGL_SINGLE_BACKDEPTH_BUFFER_NUM_VALUES = 3u,
	OGL_SINGLE_BACKDEPTH_BUFFER_DEFAULT = 0u
}
