namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_OGL_DEFAULT_SWAP_INTERVAL_SIGN : uint
{
	OGL_DEFAULT_SWAP_INTERVAL_SIGN_POSITIVE = 0u,
	OGL_DEFAULT_SWAP_INTERVAL_SIGN_NEGATIVE = 1u,
	OGL_DEFAULT_SWAP_INTERVAL_SIGN_NUM_VALUES = 2u,
	OGL_DEFAULT_SWAP_INTERVAL_SIGN_DEFAULT = 0u
}
