namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_LATENCY_INDICATOR_AUTOALIGN : uint
{
	LATENCY_INDICATOR_AUTOALIGN_DISABLED = 0u,
	LATENCY_INDICATOR_AUTOALIGN_ENABLED = 1u,
	LATENCY_INDICATOR_AUTOALIGN_NUM_VALUES = 2u,
	LATENCY_INDICATOR_AUTOALIGN_DEFAULT = 1u
}
