namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_AA_MODE_SELECTOR : uint
{
	AA_MODE_SELECTOR_MASK = 3u,
	AA_MODE_SELECTOR_APP_CONTROL = 0u,
	AA_MODE_SELECTOR_OVERRIDE = 1u,
	AA_MODE_SELECTOR_ENHANCE = 2u,
	AA_MODE_SELECTOR_MAX = 2u,
	AA_MODE_SELECTOR_NUM_VALUES = 5u,
	AA_MODE_SELECTOR_DEFAULT = 0u
}
