namespace nspector.Native.NvApi.DriverSettings;

public enum EValues_PREFERRED_PSTATE : uint
{
	PREFERRED_PSTATE_ADAPTIVE = 0u,
	PREFERRED_PSTATE_PREFER_MAX = 1u,
	PREFERRED_PSTATE_DRIVER_CONTROLLED = 2u,
	PREFERRED_PSTATE_PREFER_CONSISTENT_PERFORMANCE = 3u,
	PREFERRED_PSTATE_PREFER_MIN = 4u,
	PREFERRED_PSTATE_OPTIMAL_POWER = 5u,
	PREFERRED_PSTATE_MIN = 0u,
	PREFERRED_PSTATE_MAX = 5u,
	PREFERRED_PSTATE_NUM_VALUES = 8u,
	PREFERRED_PSTATE_DEFAULT = 5u
}
